# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" 
    schedule:
      interval: "daily"
    reviewers:
      - "adriancentrocol"
    labels:
      - "dependencies"
    registries:
      - github-nuget

registries:
  github-nuget:
    type: "nuget-feed"
    url: "https://nuget.pkg.github.com/adriancentrocol/index.json"
    token: ${{ secrets.NUGET_STORE_PAT }}
